from __future__ import annotations

ALERT_STATUS_OPEN = "open"
ALERT_STATUS_NOTIFIED = "notified"
ALERT_STATUS_ACKNOWLEDGED = "acknowledged"
ALERT_STATUS_RESOLVED = "resolved"

ALERT_LIFECYCLE_STATES = {
    ALERT_STATUS_OPEN,
    ALERT_STATUS_NOTIFIED,
    ALERT_STATUS_ACKNOWLEDGED,
    ALERT_STATUS_RESOLVED,
}
